services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facturacion_app
    restart: unless-stopped
    working_dir: /var/www
    # ELIMINA la sección 'ports' si quieres que Coolify maneje el dominio.
    # Coolify detectará el EXPOSE del Dockerfile o la config en la UI.
    expose:
      - "8000"
    environment:
      APP_URL: ${APP_URL} # Coolify inyectará esto automáticamente
      APP_ENV: production
      APP_DEBUG: "false"
      
      # Conexión a BD (Como están en la misma red 'facturacion_net', usa el nombre del servicio)
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: facturacion_sunat
      DB_USERNAME: ernesto
      DB_PASSWORD: ernesto318269.
    depends_on:
      - db
    networks:
      - facturacion_net

  db:
    image: mysql:8.0
    container_name: facturacion_db
    restart: always
    environment:
      MYSQL_DATABASE: facturacion_sunat
      MYSQL_USER: ernesto
      MYSQL_PASSWORD: ernesto318269.
      MYSQL_ROOT_PASSWORD: ernesto318269.
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - facturacion_net

volumes:
  db_data:

networks:
  facturacion_net:
    driver: bridge