services:
  # Servicio de la Aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facturacion_app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    environment:
      # Aquí sobreescribimos las variables del .env para Docker
      DB_CONNECTION: mysql
      DB_HOST: db  # IMPORTANTE: En Docker, el host es el nombre del servicio, no 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: facturacion_sunat
      DB_USERNAME: tu_usuario
      DB_PASSWORD: tu_password
    depends_on:
      - db
    networks:
      - facturacion_net

  # Servicio de Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: facturacion_db
    restart: always
    environment:
      MYSQL_DATABASE: facturacion_sunat
      MYSQL_USER: tu_usuario
      MYSQL_PASSWORD: tu_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306" # Opcional: solo si quieres acceder a la BD desde tu PC (HeidiSQL, DBeaver)
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos para que no se borren al apagar
    networks:
      - facturacion_net

volumes:
  db_data:

networks:
  facturacion_net:
    driver: bridge